import LocalizedStrings from 'react-localization';

let strings = new LocalizedStrings({
    ru:{
      searchPlaceholder:"Искать Книги, Аудиокниги, Подкасты",
      popularText: "Популярное",
      bookBestSellers: "Книжные Бестселлеры",
      videoText: "Видео", 
      booksText: "Книги",
      newsText: "Новости",
      nameText: "Название",
      authorText: "Автор",
      sourceText: "Источник",
      publishYearText: "Год издания",
      descriptionText: "Описание",
      readText: "Читать",
      downloadText: "Скачать",
      saveText: "Сохранить",
      savedText: "Сохранено",
      movePageText: "Перейти",
      viwsText: "просмотров",
      uploadDateText: "Дата добовления",
      govResourcesText: "Государственные источники информации и Новости",
      useAccount: "Используйте свою учетную запись BilimHub",
      enterEmail: "Введите свой Email адрес",
      forgotEmail: "Забыли адрес электронной почты?",
      enterPassword: "Введите пароль",
      forgotPassword: "Забыли пароль?",
      createAccout: "Создать аккаунт",
      signIn: "Войти",
      repeatPassword: "Повторите пароль",
      alreadyHave: "Уже есть аккаунт",
      signUp: "Зарегистрироваться",
      aboutUsTitle: "О нас",
      moto: " - равные возможности для всех",
      aboutDesc: "Наше видение - видение этого проекта состоит в том, чтобы помочь сельским общинам преодолеть ограничения инфраструктуры путем создания бесплатной электронной библиотечной системы, представленной в виде веб- и мобильного приложения с удобным интерфейсом. Как открытый источник, он предоставит пользователю учебные материалы, книги, литературные материалы, новости и правительственные ресурсы.",
      aboutMeet: "Знакомство с разработчиками",
      nameValeriya: "Валерия Никифорова",
      aboutBack: "Серверный разработчик",
      nameLena:"Елена Нам",
      aboutFront: "Разработчик интерфейса",
      notFound: "Не найдено! Нажмите для поиска в интернете",
      globalSearchMessage: "Поиск…Вернитесь позже, чтобы найти запрошенный материал",
      savedBooks: "Сохраненные книги",
      savedVideos: "Сохраненные видео",
      raiting: "Рейтинг",
      genre: "Жанр",
      year: "Год", 
      byPopularity: "По популярности",
      all: "Все"
    },
    kg: {
      searchPlaceholder:"Китептерди, аудиокитептерди, подкасттарды издөө",
      popularText: "Популярдуу",
      bookBestSellers: "Китеп Бестселлерлери",
      videoText: "Видео",
      booksText: "Китептер",
      newsText: "Жанылыктар",
      nameText: "Аты-жөнү",
      authorText: "Автор",
      sourceText: "Булак",
      publishYearText: "Жарыялоо жылы",
      descriptionText: "Сыпаттама",
      readText: "Оку",
      downloadText: "Көчүрү",
      saveText: "Сактоо",
      savedText: "Сакталган",
      movePageText: "Жылдыруу",
      viwsText: "көрүүлөр",
      uploadDateText: "Датасы кошулган",
      govResourcesText: "Мамлекеттик маалымат жана кабар булактары",
      useAccount: "BilimHub колдонуңуз",
      enterEmail: "Email адрести жазыңыз",
      forgotEmail: "Email адрести унуттуңузбу?",
      enterPassword: "Пароль киргизиңиз",
      forgotPassword: "Парольду унуттуңузбу?",
      createAccout: "Пароль ойлоп жазыңыз",
      signIn: "Кирүү",
      repeatPassword: "Парольду кайталап жазыңыз",
      alreadyHave: "Аккаунтунуз бар",
      signUp: "Регистрация кылуу",
      aboutUsTitle: "О нас",
      moto: " - Баарына бирдей мүмкүнчүлүк",
      aboutDesc: "  Биздин көз карашыбыз – Бул долбоордун көрүнүшү – бул интернет жана мобилдик тиркеме катары сунушталган акысыз электрондук китепкана системасын түзүү аркылуу айылдык коомчулуктарга инфраструктуранын чектөөлөрүн жеңүүгө жардам берүү. Ачык булак катары ал колдонуучуну окуу материалдары, китептер, адабий материалдар, жаңылыктар жана мамлекеттик ресурстар менен камсыз кылат.",
      aboutMeet: "Разработчиктер менен таанышуу",
      nameValeriya: "Валерия Никифорова",
      aboutBack: "Сервердин разработчиги",
      nameLena:"Елена Нам",
      aboutFront: "Интерфейстин разработчиги",
      notFound: "Табылбады! Интернетте издөө үчүн басыңыз",
      globalSearchMessage: "Издөө... Суралган материалды табуу үчүн кийинчерээк кайтып келиңиз",
      savedBooks: "Сакталган китептер",
      savedVideos: "Сакталган видеолор",
      raiting: "Рейтинг",
      genre: "Жанр",
      year: "Жыл", 
      byPopularity: "Популярдуулук",
      all: "Баары"
    },
    en: {
      searchPlaceholder:"Search Books, Audiobooks, Podcasts",
      popularText: "Popular",
      bookBestSellers: "Book Bestsellers",
      videoText: "Video",
      booksText: "Books",
      newsText: "News",
      nameText: "Title",
      authorText: "Author",
      sourceText: "Source",
      publishYearText: "Publish Year",
      descriptionText: "Description",
      readText: "Read",
      downloadText: "Download",
      saveText: "Save",
      savedText: "Saved",
      movePageText: "Move",
      viwsText: "views",
      uploadDateText: "Date added",
      govResourcesText: "State Sources of Information and News",
      useAccount: "Use your BilimHub account",
      enterEmail: "Enter the Email address",
      forgotEmail: "Forgot email?",
      enterPassword: "Enter the Password",
      forgotPassword: "Forgot password?",
      createAccout: "Create an account",
      signIn: "Sign In",
      repeatPassword: "Repeat the Password",
      alreadyHave: "Already have an account",
      signUp: "Sign Up",
      aboutUsTitle: "About Us",
      moto: " - equal opportunities to all",
      aboutDesc: "Our vision - the vision of this project is to help rural communities to overcome the infrustructure limits by creating free electronic lybrary system presented as a a web and mobile application with the user-friendly interface. As an open-source it will provide the user with educational materials, books, literature materials, news, and, governmental resources.",
      aboutMeet: "Meet the Developers",
      nameValeriya: "Valeriya Nikiforova",
      aboutBack: "Backend Developer",
      nameLena:"Elena Nam",
      aboutFront: "Frontend Developer",
      notFound: "Not found! Click to search in the Internet",
      globalSearchMessage: "Searching... Come back later to find the requested material",
      savedBooks: "Saved books",
      savedVideos: "Saved videos",
      raiting: "Raiting",
      genre: "Genre",
      year: "Year", 
      byPopularity: "Popular",
      all: "All"
    },
    tj: {
      searchPlaceholder:"Ҷустуҷӯйи китобҳо, Китобҳои аудиоӣ, Подкастҳо",
      popularText: "Машҳур",
      bookBestSellers: "Китобҳои бестселлер",
      videoText: "Видео", 
      booksText: "Китобҳо",
      newsText: "Хабарҳо",
      nameText: "Номи китоб",
      authorText: "Муаллиф",
      sourceText: "Сарчашма",
      publishYearText: "Соли нашр",
      descriptionText: "Тавсиф",
      readText: "Хондан",
      downloadText: "Сабт кардан",
      saveText: "Нигоҳ доштан",
      savedText: "Захира карда шуд",
      movePageText: "Гузаштан",
      viwsText: "назари",
      uploadDateText: "санаи иловашуда",
      govResourcesText: "Манбаъхои давлатии иттилоот ва ахбор",
      useAccount: "Ҳисоби BilimHub-и худро истифода баред",
	    enterEmail: " Суроғаи почтаи электрониро ворид кунед ",
      forgotEmail: " Почтаи электрониро фаромӯш кардед?",
      enterPassword: " Рамзро ворид кунед",
      forgotPassword: " Калидвожа фаромӯш шуд?",
      createAccout: " Аккаунта кушоед ",
      signIn: " Даромад ",
      repeatPassword: " Рамзро такрор кунед ",
      alreadyHave: " Аллакай ҳисоб доред ",
      signUp: " Қайд кардан ",
      aboutUsTitle: " Дар бораи мо ",
      moto: " - барои ҳама имкониятҳои баробар ",
      aboutDesc: " Биниши мо – диди лоиҳаи мазкур аз он иборат аст, ки ба ҷамоатҳои деҳот барои бартараф кардани маҳдудиятҳои инфрасохторӣ тавассути эҷоди системаи ройгони китобхонаҳои электронӣ, ки ҳамчун веб ва замимаи мобилӣ бо интерфейси дӯстона пешниҳод карда мешаванд, кӯмак расонанд. Ҳамчун манбаи кушода он ба корбарон маводи таълимӣ, китобҳо, маводи адабӣ, ахбор ва захираҳои давлатӣ медиҳад.",
      aboutMeet: " Бо таҳиягарон вохӯред ",
      nameValeriya: "Valeriya Nikiforova",
      aboutBack: " Таҳиягари Backend ",
      nameLena:"Elena Nam",
      aboutFront: " Таҳиягари Frontend ",
      notFound: "Пайдо нашуд! Пахш кунед барои ҷустуҷӯ дар Интернет",
      globalSearchMessage: "ҷустуҷӯ мекунем... дертар баргардед, материал ба зудй меояд",
      savedBooks: "Китобҳои захирашуда",
      savedVideos: "Видеоҳои захирашуда",
      raiting: "Рейтинг",
      genre: "Жанр",
      year: "Соли", 
      byPopularity: "Маъруфият",
      all: "Ҳама"
    }
   });
   export {strings};